# Generated by Django 3.2 on 2021-04-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('IV', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_chain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('election_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='safevote',
        ),
        migrations.AddField(
            model_name='candidates',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.blockchain'),
        ),
    ]
