# Generated by Django 3.2 on 2021-04-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0002_auto_20210419_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='id',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidate',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
    ]
