# Generated by Django 3.2 on 2021-04-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0003_auto_20210419_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
    ]
