# Generated by Django 3.2 on 2021-04-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0004_alter_candidates_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevote_app.elections'),
        ),
        migrations.DeleteModel(
            name='BlockChain',
        ),
    ]
