# Generated by Django 3.2 on 2021-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0005_auto_20210419_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AddField(
            model_name='block',
            name='index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
