# Generated by Django 3.2 on 2021-04-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0006_auto_20210419_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_chain',
            new_name='election',
        ),
    ]
