# Generated by Django 3.2 on 2021-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0007_rename_block_chain_block_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='IV',
            field=models.BinaryField(max_length=16),
        ),
        migrations.AlterField(
            model_name='block',
            name='key',
            field=models.BinaryField(max_length=16),
        ),
    ]
