# Generated by Django 3.2 on 2021-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0009_auto_20210421_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='user_id',
            field=models.CharField(default='Andrew', max_length=50),
        ),
        migrations.AddField(
            model_name='block',
            name='vote',
            field=models.CharField(default='Trump', max_length=50),
        ),
    ]
