# Generated by Django 3.2 on 2021-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevote_app', '0010_auto_20210421_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='IV',
            field=models.BinaryField(max_length=16),
        ),
        migrations.AlterField(
            model_name='block',
            name='key',
            field=models.BinaryField(max_length=16),
        ),
    ]
